blank_issues_enabled: true
contact_links:
  - name: Preguntas y Discusiones
    url: https://github.com/solecitofo/FocusFlow/discussions
    about: Usa las discusiones para preguntas generales o ideas que quieras explorar con la comunidad
